#!/bin/bash
# =============================================================================
# Password Policy Configuration Script for Rocky Linux 9
# =============================================================================
# Settings applied:
#   - Account lockout after 5 failed authentication attempts
#   - Password complexity: uppercase, lowercase, digits, special characters
#   - Minimum password length: 8 characters
#   - Password expiration: 90 days
# =============================================================================

set -euo pipefail

# Output colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()    { echo -e "${GREEN}[INFO]${NC}  $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_section() { echo -e "\n${BLUE}==> $1${NC}"; }

# Ensure the script is run as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (sudo)."
    exit 1
fi

# =============================================================================
# POLICY PARAMETERS
# =============================================================================
MAX_AUTH_TRIES=5          # Number of failed attempts before account lockout
LOCK_TIME=600             # Lockout duration in seconds (10 minutes)
MIN_LEN=8                 # Minimum password length
MIN_UPPERCASE=1           # Minimum number of uppercase characters
MIN_LOWERCASE=1           # Minimum number of lowercase characters
MIN_DIGITS=1              # Minimum number of digits
MIN_SPECIAL=1             # Minimum number of special characters
PASS_MAX_DAYS=90          # Maximum password age in days
PASS_MIN_DAYS=1           # Minimum days before a password can be changed
PASS_WARN_AGE=7           # Days before expiration to warn the user
REMEMBER=5                # Number of previous passwords to remember

# =============================================================================
# 1. INSTALL REQUIRED PACKAGES
# =============================================================================
log_section "Installing packages"

# pam is already installed on Rocky Linux 9 — only install libpwquality
dnf install -y libpwquality 2>/dev/null && \
    log_info "Package libpwquality installed." || \
    log_warn "Package already installed or an error occurred."

# =============================================================================
# 2. CONFIGURE ACCOUNT LOCKOUT ON FAILED ATTEMPTS (pam_faillock)
# =============================================================================
log_section "Configuring account lockout (pam_faillock)"

FAILLOCK_CONF="/etc/security/faillock.conf"

# Create a backup before modifying
cp -n "$FAILLOCK_CONF" "${FAILLOCK_CONF}.bak" 2>/dev/null && \
    log_info "Backup created: ${FAILLOCK_CONF}.bak" || true

# WARNING: This overwrites the entire faillock.conf file.
# A backup has been saved to ${FAILLOCK_CONF}.bak before any changes.
# NOTE: On Rocky Linux 9 with pam >= 1.4, pam_faillock reads parameters
# from this file automatically. However, we also inject them explicitly
# into PAM via a custom authselect profile (see below) for guaranteed
# enforcement — "config file" and "actual PAM behavior" must always match.
cat > "$FAILLOCK_CONF" <<EOF
# /etc/security/faillock.conf
# Generated by password_policy.sh
# NOTE: This file is fully managed by the script. Manual edits may be overwritten.

# Write failed attempts to the audit log
audit

# Apply only to local users (skip system accounts)
local_users_only

# Number of failed attempts before the account is locked
deny = ${MAX_AUTH_TRIES}

# Time window (in seconds) in which failed attempts are counted.
# Attempts outside this window are ignored.
fail_interval = 900

# Duration of the lockout in seconds (0 = permanent until manual reset)
unlock_time = ${LOCK_TIME}

# Root account is NOT locked to prevent admin lockout.
# Set to 'true' if you want to enforce lockout for root as well (higher security,
# but risks losing administrative access if root password is forgotten or brute-forced).
even_deny_root = false
EOF

log_info "faillock.conf configured: deny=${MAX_AUTH_TRIES}, unlock_time=${LOCK_TIME}s."

# ---------------------------------------------------------------------------
# Create a custom authselect profile with explicit faillock PAM configuration.
#
# Why custom profile instead of editing /etc/pam.d/ directly?
#   - authselect owns /etc/pam.d/system-auth and /etc/pam.d/password-auth
#   - Direct edits are silently overwritten on 'authselect apply-changes'
#   - A custom profile survives apply-changes and keeps authselect consistent
#
# Why write PAM templates directly (not sed on base profile)?
#   - authselect create-profile copies Jinja-like templates with {if with-faillock}
#     conditionals — sed cannot safely patch those template blocks
#   - Writing the final PAM content directly is explicit, predictable, and
#     guaranteed to produce the exact lines we want in /etc/pam.d/
# ---------------------------------------------------------------------------
CUSTOM_PROFILE="custom/hardened"
CUSTOM_PROFILE_DIR="/etc/authselect/custom/hardened"
FAILLOCK_PARAMS="deny=${MAX_AUTH_TRIES} unlock_time=${LOCK_TIME} fail_interval=900"

# Create the custom profile directory if it does not exist yet
if [[ ! -d "$CUSTOM_PROFILE_DIR" ]]; then
    authselect create-profile hardened --base-on minimal
    log_info "Custom authselect profile 'hardened' created from 'minimal'."
else
    log_info "Custom authselect profile 'hardened' already exists, updating PAM files."
fi

# Write the system-auth PAM template with explicit faillock parameters.
# This file is the source that authselect uses to generate /etc/pam.d/system-auth.
# The same content is applied to password-auth (both files must be identical
# for SSH and local logins to enforce the same policy).
write_pam_template() {
    local dest="$1"
    cat > "$dest" <<PAMEOF
# Generated by password_policy.sh — do not edit manually.
# Managed via authselect custom profile: ${CUSTOM_PROFILE}

auth        required      pam_env.so
auth        required      pam_faillock.so preauth silent ${FAILLOCK_PARAMS}
auth        [success=1 default=bad] pam_unix.so nullok
auth        [default=die] pam_faillock.so authfail ${FAILLOCK_PARAMS}
auth        sufficient    pam_faillock.so authsucc ${FAILLOCK_PARAMS}
auth        required      pam_deny.so

account     required      pam_faillock.so
account     required      pam_unix.so
account     sufficient    pam_localuser.so

password    requisite     pam_pwquality.so try_first_pass local_users_only
password    sufficient    pam_unix.so sha512 shadow nullok use_authtok
password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
session     required      pam_unix.so
PAMEOF
}

write_pam_template "${CUSTOM_PROFILE_DIR}/system-auth"
write_pam_template "${CUSTOM_PROFILE_DIR}/password-auth"
log_info "PAM templates written to custom profile with explicit faillock parameters."

# Activate the custom profile
authselect select "${CUSTOM_PROFILE}" --force
log_info "Custom authselect profile '${CUSTOM_PROFILE}' activated."

# Regenerate /etc/pam.d/ files from the custom profile templates
authselect apply-changes
log_info "authselect changes applied — /etc/pam.d/system-auth and password-auth updated."

# Verify that deny= is actually present in the live PAM file
if grep -q "deny=${MAX_AUTH_TRIES}" /etc/pam.d/system-auth; then
    log_info "Verified: deny=${MAX_AUTH_TRIES} is present in /etc/pam.d/system-auth."
else
    log_warn "Could not verify deny= in /etc/pam.d/system-auth — please check manually:"
    log_warn "  grep faillock /etc/pam.d/system-auth"
fi

# =============================================================================
# 3. CONFIGURE PASSWORD COMPLEXITY (pwquality)
# =============================================================================
log_section "Configuring password complexity (pwquality)"

PWQUALITY_CONF="/etc/security/pwquality.conf"

cp -n "$PWQUALITY_CONF" "${PWQUALITY_CONF}.bak" 2>/dev/null && \
    log_info "Backup created: ${PWQUALITY_CONF}.bak" || true

# WARNING: This overwrites the entire pwquality.conf file.
# A backup has been saved to ${PWQUALITY_CONF}.bak before any changes.
cat > "$PWQUALITY_CONF" <<EOF
# /etc/security/pwquality.conf
# Generated by password_policy.sh

# Minimum password length
minlen = ${MIN_LEN}

# Minimum number of uppercase characters (negative value = hard minimum)
ucredit = -${MIN_UPPERCASE}

# Minimum number of lowercase characters
lcredit = -${MIN_LOWERCASE}

# Minimum number of digit characters
dcredit = -${MIN_DIGITS}

# Minimum number of special (other) characters
ocredit = -${MIN_SPECIAL}

# Minimum number of character classes required
minclass = 4

# Maximum number of consecutive identical characters allowed
maxrepeat = 3

# Maximum number of consecutive characters from the same class
maxclassrepeat = 4

# Reject passwords containing the username
usercheck = 1

# Minimum number of characters that must differ from the previous password
difok = 4

# Enable dictionary-based weak password check
dictcheck = 1

# Reject passwords containing GECOS user information (full name, etc.)
gecoscheck = 1
EOF

log_info "pwquality.conf configured: minlen=${MIN_LEN}, ucredit/lcredit/dcredit/ocredit=-1."

# =============================================================================
# 4. CONFIGURE PASSWORD HISTORY (pam_pwhistory)
# =============================================================================
log_section "Configuring password history (pam_pwhistory)"

PWHISTORY_CONF="/etc/security/pwhistory.conf"

if [[ -f "$PWHISTORY_CONF" ]]; then
    cp -n "$PWHISTORY_CONF" "${PWHISTORY_CONF}.bak" 2>/dev/null || true

    # Update the 'remember' parameter if it exists, otherwise append it
    if grep -q "^remember" "$PWHISTORY_CONF"; then
        sed -i "s/^remember.*/remember = ${REMEMBER}/" "$PWHISTORY_CONF"
    else
        echo "remember = ${REMEMBER}" >> "$PWHISTORY_CONF"
    fi
    log_info "pwhistory.conf: remember=${REMEMBER} previous passwords."
else
    # Fallback: inject pam_pwhistory directly into PAM configuration.
    # WARNING: In Rocky Linux 9, directly editing /etc/pam.d/ files is not
    # recommended when using authselect — changes may be overwritten by
    # 'authselect apply-changes'. Prefer using an authselect custom profile
    # with pam_pwhistory support for a production environment.
    PAM_PASSWD="/etc/pam.d/password-auth"
    if ! grep -q "pam_pwhistory" "$PAM_PASSWD"; then
        sed -i '/^password.*pam_pwquality/a password    requisite     pam_pwhistory.so use_authtok remember='"${REMEMBER}"' enforce_for_root' "$PAM_PASSWD"
        log_info "pam_pwhistory added to password-auth (remember=${REMEMBER})."
    else
        log_info "pam_pwhistory already present in password-auth."
    fi
fi

# =============================================================================
# 5. CONFIGURE PASSWORD EXPIRATION (/etc/login.defs)
# =============================================================================
log_section "Configuring password expiration (login.defs)"

LOGIN_DEFS="/etc/login.defs"
cp -n "$LOGIN_DEFS" "${LOGIN_DEFS}.bak" 2>/dev/null && \
    log_info "Backup created: ${LOGIN_DEFS}.bak" || true

# Helper: update an existing key or append it if not found
set_login_def() {
    local key="$1"
    local value="$2"
    if grep -q "^${key}" "$LOGIN_DEFS"; then
        sed -i "s/^${key}[[:space:]].*/${key}\t${value}/" "$LOGIN_DEFS"
    else
        echo -e "${key}\t${value}" >> "$LOGIN_DEFS"
    fi
}

set_login_def "PASS_MAX_DAYS" "$PASS_MAX_DAYS"
set_login_def "PASS_MIN_DAYS" "$PASS_MIN_DAYS"
set_login_def "PASS_WARN_AGE" "$PASS_WARN_AGE"

log_info "login.defs: MAX_DAYS=${PASS_MAX_DAYS}, MIN_DAYS=${PASS_MIN_DAYS}, WARN_AGE=${PASS_WARN_AGE}."

# =============================================================================
# 6. APPLY EXPIRATION POLICY TO EXISTING LOCAL USERS
# =============================================================================
log_section "Applying policy to existing local users"

# Process all users with UID >= 1000 and a valid login shell
while IFS=: read -r username _ uid _ _ homedir shell; do
    if [[ "$uid" -ge 1000 && "$shell" != "/sbin/nologin" && "$shell" != "/bin/false" ]]; then
        chage --maxdays "$PASS_MAX_DAYS" \
              --mindays "$PASS_MIN_DAYS" \
              --warndays "$PASS_WARN_AGE" \
              "$username" 2>/dev/null && \
            log_info "User '$username': policy applied." || \
            log_warn "Could not apply policy to '$username'."
    fi
done < /etc/passwd

# =============================================================================
# 7. SUMMARY REPORT
# =============================================================================
log_section "Applied policy summary"

echo ""
echo "┌─────────────────────────────────────────────────────────┐"
echo "│              APPLIED SECURITY POLICY SETTINGS           │"
echo "├──────────────────────────────────────┬──────────────────┤"
printf "│ %-38s │ %-16s │\n" "Parameter" "Value"
echo "├──────────────────────────────────────┼──────────────────┤"
printf "│ %-38s │ %-16s │\n" "Lockout after N failed attempts"     "${MAX_AUTH_TRIES} attempts"
printf "│ %-38s │ %-16s │\n" "Lockout duration"                    "${LOCK_TIME} sec"
printf "│ %-38s │ %-16s │\n" "Minimum password length"             "${MIN_LEN} chars"
printf "│ %-38s │ %-16s │\n" "Uppercase characters (min)"          "${MIN_UPPERCASE}"
printf "│ %-38s │ %-16s │\n" "Lowercase characters (min)"          "${MIN_LOWERCASE}"
printf "│ %-38s │ %-16s │\n" "Digits (min)"                        "${MIN_DIGITS}"
printf "│ %-38s │ %-16s │\n" "Special characters (min)"            "${MIN_SPECIAL}"
printf "│ %-38s │ %-16s │\n" "Password history"                    "${REMEMBER} previous"
printf "│ %-38s │ %-16s │\n" "Password expiration"                 "${PASS_MAX_DAYS} days"
printf "│ %-38s │ %-16s │\n" "Min days before password change"     "${PASS_MIN_DAYS} day"
printf "│ %-38s │ %-16s │\n" "Expiration warning"                  "${PASS_WARN_AGE} days before"
echo "└──────────────────────────────────────┴──────────────────┘"

echo ""
log_info "Password security policy applied successfully!"
log_warn "It is recommended to restart PAM sessions or re-login."
echo ""
log_info "To manually unlock a user account:"
echo "       faillock --user <username> --reset"
echo ""
log_info "To check account lockout status:"
echo "       faillock --user <username>"
echo ""
